#!/bin/sh
echo 'connectRE by DerBerg (v2 — 17th of February 2021)'
#$1 = 1. Parameter
INTERFACE=$(ls /sys/class/net | grep wl) #Alternatively use ip link

[ "$1" = "down" ] && {
        echo 'shutting down network interface..'
        sudo ifconfig $INTERFACE down
} || {
        echo 'reenabling network interface..'
        sudo ifconfig $INTERFACE up
        sudo dhclient $INTERFACE
        echo 'network interface' $INTERFACE 'is up again!'
}
